### ISSUE TITLE
If one MRT archive is unreachable, the entire getter process fails

### ISSUE THREAD

**Issue by jwbensley** [jwbensley/dfz_name_and_shame#100]
Couldn't reach route-views, so no MRTs from any archives were collected and passed - could we collect and pass but not generate stats and raise an error?

```
2022-04-14 12:23:33,104|INFO|Downloading http://archive.routeviews.org/route-views.linx/bgpdata/2022.04/UPDATES/updates.20220413.0000.bz2 to /media/usb0/downloads/LINX/updates.20220413.0000.bz2
2022-04-14 12:23:38,016|INFO|Couldn't connect to MRT server: HTTPConnectionPool(host='archive.routeviews.org', port=80): Max retries exceeded with url: /route-views.linx/bgpdata/2022.04/UPDATES/updates.20220413.0000.bz2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007faf02da60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/opt/pypy3.8-v7.3.7-aarch64/lib/pypy3.8/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/pypy3.8-v7.3.7-aarch64/lib/pypy3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/pypy3.8-v7.3.7-aarch64/lib/pypy3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

**Comment by jwbensley** [comment]
Fixed by PR #159
