### ISSUE TITLE
Git pull before adding report

### ISSUE THREAD

**Issue by jwbensley** [jwbensley/dfz_name_and_shame#137]
Do a git pull first, to ensure local repo is update to, otherwise git compains no ff

**Comment by jwbensley** [comment]
```
2022-06-15 07:06:19,282|INFO|Starting logging for report generation and posting script at level INFO
Traceback (most recent call last):
  File "/opt/dnas/scripts/git_reports.py", line 288, in <module>
    main()
  File "/opt/dnas/scripts/git_reports.py", line 262, in main
    check_git()
  File "/opt/dnas/scripts/git_reports.py", line 33, in check_git
    git.pull()
  File "/opt/dnas/scripts/../dnas/git.py", line 230, in pull
    f"stderr: {ret.stderr.decode()}"
ChildProcessError: Couldn't pull from remote branch main
args: ['git', 'pull']
stdout: 
stderr: From github.com:DFZ-Name-and-Shame/dnas_stats
   bfab51a..86c02db  main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

**Comment by jwbensley** [comment]
This is missing a `git clean -f`
