### ISSUE TITLE
Whois failure

### ISSUE THREAD

**Issue by jwbensley** [jwbensley/dfz_name_and_shame#192]
```
Creating docker_dnas_stats_run ... done
2023-10-17 13:01:16,567|INFO|Starting logging for report generation and posting script at level INFO
Traceback (most recent call last):
  File "/opt/dnas/dnas/scripts/git_reports.py", line 289, in <module>
    main()
  File "/opt/dnas/dnas/scripts/git_reports.py", line 267, in main
    generate(args["ymd"])
  File "/opt/dnas/dnas/scripts/git_reports.py", line 62, in generate
    txt_report = report.gen_txt_report(day_stats)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dnas/dnas/scripts/../dnas/report.py", line 449, in gen_txt_report
    whois_cache[asn] = whois.as_lookup(int(asn))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dnas/dnas/scripts/../dnas/whois.py", line 29, in as_lookup
    ret = subprocess.check_output(cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pypy3.10-v7.3.12-linux64/lib/pypy3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/pypy3.10-v7.3.12-linux64/lib/pypy3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['whois', 'AS426000003']' returned non-zero exit status 1.
ERROR: 1
```

**Comment by jwbensley** [comment]
This happens because the ASNs are unallocated by IANA to any RIR
