### ISSUE TITLE
Long running parsing issue - Python switches between list and OrderedDict

### ISSUE THREAD

**Issue by jwbensley** [jwbensley/dfz_name_and_shame#56]
When running parse_mrts.py in a venv, or with PyPy, one must parse the MRT data as OrderedDict.

The following code from method `parse_upd_dump()` in class `mrt_parser` produces the following error output (this works in the non-venv scenario though):

```Python3
class mrt_parser:
    ...
    @staticmethod
    def parse_upd_dump(filename: str = None) -> 'mrt_stats':
        ...
        for idx, mrt_e in enumerate(mrt_entries):
            ...
            print(mrt_e.data["timestamp"])
            ts = mrt_parser.posix_to_ts(
                mrt_e.data["timestamp"][0]
            )
```

Output:
```
{1641001800: '2022-01-01 02:50:00'}
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/bensley/GitHub/dnas/scripts/../dnas/mrt_parser.py", line 281, in parse_upd_dump
    mrt_e.data["timestamp"][0]
KeyError: 0
"""
```

When running with Python3 instead of PyPy, or with Python3 but not in a venv, the MRT data must be passed as a list.

The following code produces the following output (this works in the venv scenario though):

```Python3
class mrt_parser:
    ...
    @staticmethod
    def parse_upd_dump(filename: str = None) -> 'mrt_stats':
        ...
        for idx, mrt_e in enumerate(mrt_entries):
            ...
            print(mrt_e.data["timestamp"])
            ts = mrt_parser.posix_to_ts(
                next(iter(mrt_e.data["timestamp"].items()))[0]
            )
```

Output:
```
[1641001800, '2022-01-01 02:50:00']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/bensley/GitHub/dnas/scripts/../dnas/mrt_parser.py", line 280, in parse_upd_dump
    next(iter(mrt_e.data["timestamp"].items()))[0]
AttributeError: 'list' object has no attribute 'items'
"""
```

**Comment by jwbensley** [comment]
This is no longer a problem.
